
module DataMapper
  module Form
    module Elements
      class Tag
        
        VALID_TITLE_KEYS = :title, :label, :legend, :caption
        IGNORE_CLASSES_ON_ELEMENTS = :form, :label
      
        attr_accessor :name, :options
            
        def initialize name, options = {}
          @name, @options, @attributes = name, options, options[:attributes]
        end
      
        ##
        # Render final markup of this element or 'tag'.
      
        def render
          @attributes[:class] = classes
          closure = self_closing? ? " />" : ">#{inner_html}</#{@name}>"
          tag = before << render_title << "<#{@name} #{@attributes.to_html_attributes}" << closure << description << after << "\n"
        end
        alias :to_s :render
      
        ##
        # Wither or not a tag is self-closing (<br />).
      
        def self_closing?
          @options[:self_closing]
        end
      
        ##
        # The inner HTML of this tag, only available for
        # elements which are not self-closing.
      
        def inner_html
          attribute :value, '' unless self_closing?
        end
      
        ##
        # Attempt to pull title from :title, :label, :legend, etc.
      
        def title
          @title ||= attribute title_key
        end
        
        ##
        # Attempt to find and return valid title key or ''.
        
        def title_key
          VALID_TITLE_KEYS.find { |key| @attributes.has_key? key }
        end
      
        ##
        # Render title for this element.
      
        def render_title
          if title.blank?
            ''
          else
            Elements.label title, :for => @attributes[:name], :required => required?
          end
        end
            
        ##
        # Is the element required.
      
        def required?
          attribute :required, false
        end
      
        ##
        # Description for this attribute.
      
        def description
          if desc = attribute(:description, false)
            Elements.desc desc
          else
            ''
          end
        end
      
        ##
        # Markup before the element.
      
        def before
          attribute :before, ''
        end
      
        ##
        # Markup after the element.
      
        def after
          attribute :after, ''
        end
        
        ##
        # Returns user generated classes as well as those generated by
        # dm-forms for styling consistancy.
      
        def classes
          @classes ||= [@attributes[:class], generate_classes].join(' ').strip if should_add_classes?
        end
              
        private
        
        ##
        # Generates element class(es) such as form-submit.
                
        def generate_classes
          suffix = @name == :input ? @attributes[:type] : @name
          "form-#{suffix} form-#{@attributes[:name]}"
        end
      
        ##
        # Wither or not classes should be added to this element.
      
        def should_add_classes?
          !IGNORE_CLASSES_ON_ELEMENTS.include? @name
        end
      
        ##
        # Return an +attribute+ or its +default+ value, removing
        # it from @attributes so that final attributes rendered
        # within the HTML are not cluttered with ad-hoc keys.
      
        def attribute attribute, default = nil
          if attr = @attributes.delete(attribute)
            attr
          else
            default
          end   
        end
      
      end
    end
  end
end
